remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title:  LLMs for Sensor Time Series Data
description: Project for UCLA ECE M202A (Fall 2024)
